//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int BId { get; set; }
        public string BTitle { get; set; }
        public string BCategory { get; set; }
        public string BUrl { get; set; }
    }
}
